title = "ilil"

[owner]
name = "username"
mail = "username@example.org"
description = "This is an insta-like image log. :^)"

[server]
host = "localhost"
port = "8080"
password = "hackme"
itemsPerPage = 100
enableDownload = false
path = "/home/lennart/ilil"
